name: Deploy Next.js to Hostinger via FTP

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: 📂 Sync files (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 45.130.228.221
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          state-name: .ftp-deploy-sync-state.json
          security: loose
          protocol: ftp
          port: 21
          exclude: |
            **/videos/**

